# Generated by Django 4.1.3 on 2022-11-19 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecomapp', '0007_alter_jobapplication_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='workdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('sdate', models.DateField()),
                ('ldate', models.DateField()),
                ('details', models.TextField(max_length=200)),
                ('pay', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tailor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
