# Generated by Django 4.1.3 on 2022-11-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_workdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='workdetails',
            name='tailor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.tailor'),
        ),
    ]
